# Generated by Django 4.1.7 on 2023-04-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_photos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
