# Generated by Django 4.1.7 on 2023-04-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_photo_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
