# Generated by Django 4.1.7 on 2023-04-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_photo_photo_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_src',
            field=models.ImageField(blank=True, null=True, upload_to='photo_src'),
        ),
    ]
