# Generated by Django 4.1.7 on 2023-04-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_photo_photo_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_src',
        ),
    ]
