# Generated by Django 4.1.7 on 2023-04-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_photo_photo_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_src',
            field=models.ImageField(upload_to=''),
        ),
    ]
