# Generated by Django 4.2 on 2023-05-31 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_photo_photo_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_caption',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_title',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(blank=True, default='', max_length=255)),
                ('post_caption', models.TextField(blank=True, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.photo')),
            ],
        ),
    ]
