# Generated by Django 4.2 on 2023-05-31 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_photo_post_alter_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
