# Generated by Django 4.2 on 2023-06-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_post_photo_alter_photo_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo_src',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.post'),
            preserve_default=False,
        ),
    ]
